name: Ci Pipeline

on: 
  push:
    branches: [main]


jobs: 
  build: 
    runs-on: ubuntu-latest


    steps: 
      - name: Checkout code
        run: git checkout ${{ github.head_ref }}

      - name: Setup Node js 
        run: npm install -g @actions/setup-node@v4
        with:
          node-version: 22


      - name: Install dependcies
        run: npm install 


      - name: Run tests
        run: npm test        